INSERT INTO CLASSROOM (trainerName) VALUES ('Matt')
INSERT INTO CLASSROOM (trainerName) VALUES ('Jon')

INSERT INTO TRAINEE (traineeName) VALUES ('Ben')
INSERT INTO TRAINEE (traineeName) VALUES ('Joe')
INSERT INTO TRAINEE (traineeName) VALUES ('Gareth')

INSERT INTO CLASSROOM_TRAINEE (CLASSROOM_CLASSROOMID, TRAINEES_TRAINEEID) VALUES (1, 1)
INSERT INTO CLASSROOM_TRAINEE (CLASSROOM_CLASSROOMID, TRAINEES_TRAINEEID) VALUES (1, 2)
INSERT INTO CLASSROOM_TRAINEE (CLASSROOM_CLASSROOMID, TRAINEES_TRAINEEID) VALUES (2, 3)